name: 'Deploy to jameslittle.org'
concurrency: production

on:
  push:
    branches:
      - release/*
  workflow_dispatch:
      
jobs:

  deployment:
    runs-on: ubuntu-latest
    environment: production
    steps:          
      - name: Create SSH key
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          SSH_KNOWN_HOSTS: ${{ secrets.SSH_KNOWN_HOSTS }}
        run: |
          install -m 600 -D /dev/null ~/.ssh/id_rsa
          echo "$SSH_PRIVATE_KEY" > ~/.ssh/id_rsa
          echo "$SSH_KNOWN_HOSTS" > ~/.ssh/known_hosts
          
      - name: Write VPN Files
        env:
          OVPN: ${{ secrets.OVPN_GITHUB }}
        run: |
          mkdir -p ~/.ssh
          echo "$OVPN" > github.ovpn
          
      - name: Install Open VPN
        run: |
          sudo apt-get install openvpn
          
      - name: Start Open VPN 3
        run: |
          sudo openvpn --config "github.ovpn" --log "vpn.log" --daemon
          
      - name: Wait for VPN Connection
        env:
          SSH_HOST: ${{ secrets.SSH_HOST }}
        run: |
          echo Host: "$SSH_HOST"
          until ping -c1 "$SSH_HOST"; do sleep 2; done
          
      - name: SSH & Run Script
        env:           
          SSH_USERNAME: ${{ secrets.SSH_USERNAME }}
          SSH_PORT: ${{ secrets.SSH_PORT }}
          SSH_HOST: ${{ secrets.SSH_HOST }}
        run: |
          ssh "$SSH_USERNAME"@"$SSH_HOST" -p"$SSH_PORT" 'gh-update.sh'
          
      - name: Kill VPN Connection
        run: |
          sudo chmod 777 vpn.log
          sudo killall openvpn
          
      - name: Upload VPN logs
        uses: actions/upload-artifact@v2
        if: always()
        with:
          name: VPN logs
          path: vpn.log
